{{- if .Values.kvCacheManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kv-cache-manager
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kv-cache-manager
spec:
  selector:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: kv-cache-manager
  ports:
    - name: zmq
      protocol: TCP
      port: {{ .Values.kvCacheManager.service.port }}
      targetPort: zmq
    - name: http
      protocol: TCP
      port: {{ .Values.kvCacheManager.service.httpPort }}
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kv-cache-manager
  namespace: {{ .Release.Namespace | default .Values.namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: kv-cache-manager
spec:
  replicas: {{ .Values.kvCacheManager.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: kv-cache-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: kv-cache-manager
    spec:
      containers:
        - name: manager
          image: "{{ .Values.kvCacheManager.image.repository }}:{{ .Values.kvCacheManager.image.tag }}"
          imagePullPolicy: {{ .Values.kvCacheManager.image.pullPolicy }}
          ports:
            - name: zmq
              containerPort: {{ .Values.kvCacheManager.service.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.kvCacheManager.service.httpPort }}
              protocol: TCP
          env:
            - name: HF_HOME # for chat-completions tokenizer cache
              value: /tmp/huggingface
            - name: MODEL_NAME
              value: {{ .Values.vllm.model.name | quote }}
            - name: ZMQ_ENDPOINT
              # Bind locally on all interfaces for a central socket
              value: "tcp://*:{{ .Values.kvCacheManager.service.port }}"
            - name: ZMQ_TOPIC
              value: {{ .Values.kvCacheManager.zmqTopic | quote }}
            - name: POOL_CONCURRENCY
              value: {{ .Values.kvCacheManager.poolConcurrency | quote }}
            - name: PYTHONHASHSEED
              value: {{ .Values.pythonHashSeed | quote }}
            - name: BLOCK_SIZE
              value: "{{ .Values.vllm.blockSize }}"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ include "chart.secretKeyName" . }}
          resources:
            {{- toYaml .Values.kvCacheManager.resources | nindent 12 }}
{{- end }}
