apiVersion: v1
kind: Service
metadata:
  name: vllm-storage-svc
  labels:
    app: vllm-storage
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: default
  selector:
    app: vllm-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-storage
  labels:
    app: vllm-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm-storage
  template:
    metadata:
      labels:
        app: vllm-storage
    spec:
      securityContext:
        fsGroup: 1001060000
      containers:
      - name: vllm
        image: vllm/vllm-openai:v0.12.0
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install https://raw.githubusercontent.com/kfirtoledo/llm-d-kv-cache-manager/connector/kv_connectors/llmd_fs_backend/wheels/llmd_fs_connector-0.1.0-cp312-cp312-linux_x86_64.whl
          vllm serve meta-llama/Meta-Llama-3.1-70B \
          --tensor-parallel-size 4 \
          --trust-remote-code \
          --enable-chunked-prefill \
          --gpu-memory-utilization 0.85 \
          --kv-transfer-config '{
            "kv_connector": "OffloadingConnector",
            "kv_role": "kv_both",
            "kv_connector_extra_config": {
              "spec_name": "SharedStorageOffloadingSpec",
              "shared_storage_path": "/mnt/files-storage/kv-cache/",
              "block_size": 256,
              "threads_per_gpu": "64",
              "spec_module_path":"llmd_fs_backend.spec"
            }
          }'
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: HF_TOKEN
        - name: HF_HOME
          value: /mnt/pvc/hf
        - name: VLLM_LOGGING_LEVEL
          value: "INFO"
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "128"
            memory: 400Gi
            nvidia.com/gpu: "4"
          requests:
            cpu: "64"
            memory: 100Gi
            nvidia.com/gpu: "4"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /mnt/pvc
          name: model-storage
        - mountPath: /mnt/files-storage
          name: files-storage
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 80Gi
      - name: model-storage
        persistentVolumeClaim:
          claimName: vllm-cache
      - name: files-storage
        persistentVolumeClaim:
          claimName: pvc-storage-files
